// RootLayout.js
import { Inter } from 'next/font/google';
import './globals.css';
import HeaderOLD from '@/app/components/HeaderOLD';
import { Amplify } from 'aws-amplify';
import config from '../amplifyconfiguration.json';
import { CurrentAuthenticatedUser } from '@/app/functions/CheckUserAuth';
import { stringifyQuery } from 'next/dist/server/server-route-utils';
import { getUserRole } from '@/app/functions/getUserRole';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        </body>
        </html>
    );
};

// Export a named constant for use in getServerSideProps
export const withRootLayout = (Component) => ({ ...pageProps }) => (
    <RootLayout>
        <Component {...pageProps} />
    </RootLayout>
);

export default RootLayout;
